-- ==========================================
-- 0. 拡張機能の有効化 (Extensions)
-- ==========================================
create extension if not exists pgcrypto;

-- ==========================================
-- 1. users: ユーザー基本情報
-- ==========================================
create table public.users (
  id uuid references auth.users on delete cascade not null primary key,
  name text not null,
  email text unique not null,
  profile_text varchar(160),
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS 有効化
alter table public.users enable row level security;

-- ポリシー定義
CREATE POLICY "ユーザープロフィールは誰でも閲覧可能" ON public.users
  FOR SELECT USING (true);

CREATE POLICY "ユーザーは自身のプロフィールのみ更新可能" ON public.users
  FOR UPDATE TO authenticated 
  USING ( (select auth.uid()) = id )
  WITH CHECK ( (select auth.uid()) = id );

-- ==========================================
-- 2. tweets: ツイート・リプライ投稿
-- ==========================================
create table public.tweets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users on delete cascade not null,
  parent_id bigint references public.tweets on delete cascade,
  content varchar(140) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS 有効化
alter table public.tweets enable row level security;

-- ポリシー定義
CREATE POLICY "ツイートは誰でも閲覧可能" ON public.tweets
  FOR SELECT USING (true);

CREATE POLICY "ログイン済みユーザーのみ投稿可能" ON public.tweets
  FOR INSERT TO authenticated 
  WITH CHECK ( (select auth.uid()) = user_id );

CREATE POLICY "投稿者本人のみ削除可能" ON public.tweets
  FOR DELETE TO authenticated 
  USING ( (select auth.uid()) = user_id );

-- ==========================================
-- 3. likes: ツイートへの「いいね」
-- ==========================================
create table public.likes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users on delete cascade not null,
  tweet_id bigint references public.tweets on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, tweet_id)
);

-- RLS 有効化
alter table public.likes enable row level security;

-- ポリシー定義
CREATE POLICY "いいねは誰でも閲覧可能" ON public.likes
  FOR SELECT USING (true);

CREATE POLICY "ログイン済みユーザーのみ「いいね」可能" ON public.likes
  FOR INSERT TO authenticated 
  WITH CHECK ( (select auth.uid()) = user_id );

CREATE POLICY "本人のみ「いいね」を解除可能" ON public.likes
  FOR DELETE TO authenticated 
  USING ( (select auth.uid()) = user_id );

-- ==========================================
-- 4. follows: フォロー・フォロワー関係
-- ==========================================
create table public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid references public.users on delete cascade not null,
  followee_id uuid references public.users on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(follower_id, followee_id),
  check(follower_id <> followee_id)
);

-- RLS 有効化
alter table public.follows enable row level security;

-- ポリシー定義
CREATE POLICY "フォロー関係は誰でも閲覧可能" ON public.follows
  FOR SELECT USING (true);

CREATE POLICY "ログイン済みユーザーのみフォロー可能" ON public.follows
  FOR INSERT TO authenticated 
  WITH CHECK ( (select auth.uid()) = follower_id );

CREATE POLICY "本人のみフォローを解除可能" ON public.follows
  FOR DELETE TO authenticated 
  USING ( (select auth.uid()) = follower_id );

-- ==========================================
-- 5. トリガー・関数
-- ==========================================

-- Supabase Auth (auth.users) と public.users の自動同期トリガー
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, name, email)
  values (new.id, new.raw_user_meta_data->>'name', new.email);
  return new;
end;
$$ language plpgsql security definer set search_path = public;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ==========================================
-- 6. Storage: アバター画像保存
-- ==========================================

-- Storage バケットの作成 (avatars)
-- insert into storage.buckets (id, name, public) 
-- values ('avatars', 'avatars', true)
-- on conflict (id) do nothing;
-- ※ ローカル環境で SQL によるバケット作成ができないケースに備え、CLI config または手動を推奨する場合があるが、
--   ここでは IaC として明文化する。

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- Storage RLS ポリシー
-- 1. 誰でも閲覧可能
CREATE POLICY "アバター画像は誰でも閲覧可能" ON storage.objects
  FOR SELECT USING (bucket_id = 'avatars');

-- 2. 認証済みユーザーは自分のフォルダにのみアップロード・更新・削除可能
-- フォルダ名をユーザーID (auth.uid()) と一致させる設計
CREATE POLICY "ユーザーは自身のアバターのみ管理可能" ON storage.objects
  FOR ALL TO authenticated 
  USING (bucket_id = 'avatars' AND (storage.foldername(name))[1] = (select auth.uid())::text)
  WITH CHECK (bucket_id = 'avatars' AND (storage.foldername(name))[1] = (select auth.uid())::text);
